# Generated by Django 4.1.2 on 2023-06-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InformacionCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubOpcionLlamada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Validacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sub_opcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="validaciones",
                        to="CU17.subopcionllamada",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpcionLlamada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                (
                    "seleccionada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="CU17.subopcionllamada",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Llamada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="CU17.cliente"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cliente",
            name="informacion_cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="CU17.informacioncliente",
            ),
        ),
        migrations.CreateModel(
            name="CategoriaLlamada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opcionSeleccionada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="CU17.opcionllamada",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CambioEstado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField()),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="CU17.estado"
                    ),
                ),
                (
                    "llamada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="cambios_estado",
                        to="CU17.llamada",
                    ),
                ),
            ],
        ),
    ]
