# Generated by Django 4.2 on 2023-12-06 19:03

import CU17.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubOpcionLlamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            bases=(models.Model, CU17.models.IAgregado),
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('sub_opcion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='validaciones', to='CU17.subopcionllamada')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionLlamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('seleccionada', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='CU17.subopcionllamada')),
            ],
        ),
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraInicio', models.DateTimeField(auto_now=True)),
                ('duracion', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='CU17.cliente')),
                ('estadoActual', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='llamada', related_query_name='estado', to='CU17.estado')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datoAValidar', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='informacion_cliente', to='CU17.cliente')),
                ('validacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='CU17.validacion')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaLlamada',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('opcionSeleccionada', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='CU17.opcionllamada')),
            ],
        ),
        migrations.CreateModel(
            name='CambioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraInicio', models.DateTimeField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='CU17.estado')),
                ('llamada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='CU17.llamada')),
            ],
        ),
        migrations.CreateModel(
            name='Cancelada',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('CU17.estado',),
        ),
        migrations.CreateModel(
            name='EnCurso',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('CU17.estado',),
        ),
        migrations.CreateModel(
            name='Finalizada',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('CU17.estado',),
        ),
        migrations.CreateModel(
            name='Iniciada',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('CU17.estado',),
        ),
    ]
