# Generated by Django 4.2.6 on 2023-12-06 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CU17", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cambioestado",
            name="llamada",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="cambios_estado",
                to="CU17.llamada",
            ),
        ),
        migrations.AlterField(
            model_name="llamada",
            name="duracion",
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
