# Generated by Django 4.1.2 on 2023-06-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CU17", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoriallamada",
            name="id",
        ),
        migrations.AddField(
            model_name="categoriallamada",
            name="nombre",
            field=models.CharField(
                default="fd", max_length=30, primary_key=True, serialize=False
            ),
        ),
    ]
