# Generated by Django 4.1.2 on 2023-06-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CU17", "0002_remove_categoriallamada_id_categoriallamada_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="validacion",
            name="nombre",
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categoriallamada",
            name="nombre",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
