# Generated by Django 4.2.6 on 2023-12-06 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CU17", "0003_alter_llamada_estadoactual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cambioestado",
            name="llamada",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cambios_estado",
                to="CU17.llamada",
            ),
        ),
    ]
