# Generated by Django 4.1.2 on 2023-06-24 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CU17", "0003_validacion_nombre_alter_categoriallamada_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="informacioncliente",
            name="datoAValidar",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="informacioncliente",
            name="validacion",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.RESTRICT,
                to="CU17.validacion",
            ),
            preserve_default=False,
        ),
    ]
