# Generated by Django 4.1.2 on 2023-06-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CU17", "0004_informacioncliente_datoavalidar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llamada",
            name="fechaInicio",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
