# Generated by Django 4.2.6 on 2023-12-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CU17", "0004_alter_cambioestado_llamada"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opcionllamada",
            name="seleccionada",
        ),
        migrations.AddField(
            model_name="subopcionllamada",
            name="opcion",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="CU17.opcionllamada",
            ),
            preserve_default=False,
        ),
    ]
