# Generated by Django 4.1.2 on 2023-06-26 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CU17", "0007_alter_llamada_duracion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="informacion_cliente",
        ),
        migrations.AddField(
            model_name="informacioncliente",
            name="cliente",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="informacion_cliente",
                to="CU17.cliente",
            ),
            preserve_default=False,
        ),
    ]
