# Generated by Django 4.1.2 on 2023-06-26 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CU17", "0008_remove_cliente_informacion_cliente_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cambioestado",
            old_name="fecha_hora",
            new_name="fechaHoraInicio",
        ),
        migrations.RenameField(
            model_name="estado",
            old_name="name",
            new_name="nombre",
        ),
        migrations.RenameField(
            model_name="llamada",
            old_name="fechaInicio",
            new_name="fechaHoraInicio",
        ),
    ]
